name: "Create GitHub App Token"
description: "Generates a GitHub App token using the specified app ID and private key, with an optional owner."

inputs:
  app-id:
    description: "The GitHub App ID"
    required: true
  private-key:
    description: "The GitHub App private key"
    required: true
  owner:
    description: "Optional: The repository owner (if needed)"
    required: false

outputs:
  token:
    description: "The generated GitHub App token"
    value: ${{ steps.set_output_token.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Create App token
      id: create_token
      uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ${{ inputs.owner }}

    - name: Set output token
      id: set_output_token
      shell: bash
      run: echo "token=${{ steps.create_token.outputs.token }}" >> $GITHUB_OUTPUT
